config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: 'lists#index'
  resources :lists, only: [:index, :new, :show, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: [:edit, :create, :update, :show, :destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def show
    @bookmarks = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      raise
      render :new
    end
  end

  def edit
    @bookmarks = Bookmark.find(params[:id])
  end

  def update
    if @bookmarks.update(bookmark_params)
      redirect_to bookmark_path(@bookmarks)
    else
      render :new
    end
  end

  def destroy
    @bookmarks.destroy
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_lists, only: [:edit, :show, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @lists = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_lists
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class=banner>
  <h4>Add a new movie bookmark:</h4>

  <div class=movie-simple-form>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie, collection: Movie.all %>
      <%= f.button :submit %>
    <% end %>
  </div>

  <div class=back-to-lists>
    <%= link_to 'Back to all lists', lists_path(@list) %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: url(https://images.pexels.com/photos/7991582/pexels-photo-7991582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
  <div class="container" >
    <h1>Save any kind of movies !</h1>
  </div>
</div>

<div class= "container-list">
  <h3>My lists:</h3>

  <div class="new-list-btn">
    <%= link_to 'Create a new list', new_list_path(@list), class: "btn btn-success float-right" %>
  </div>


    <div class="cards-container">
  <% @lists.each do |m| %>
    <div class="my-cards">
      <div class="my-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/7991582/pexels-photo-7991582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
        <%= link_to m.name, list_path(m) %>
      </div>
  <% end %>
    </div>

</div>

app/views/lists/new.html.erb
<div class=container-new-list>
  <div class="new-list bg-white rounded p-3 shadow" style="width: 600px">
    <h1>Create a new <strong>list</strong> !</h1>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.submit "Submit", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
  <div class="banner" style="background-image: url(https://images.pexels.com/photos/7991582/pexels-photo-7991582.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2)">
    <div class="container">
      <h1><%=@list.name%></h1>
    </div>
  </div>

  <ul>
    <% @list.bookmarks.each do |bookmark| %>
      <li><%= bookmark.movie.title %>
      <%= bookmark.comment %></li>
    <% end %>
  </div>

  </ul>

<div class="buttons">
  <div class="btn btn-dark">
    <%= link_to 'Delete list',
    list_path(@lists),
    data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
  </div>

  <div class="btn btn-dark">
    <%= link_to 'Add a movie', new_list_bookmark_path(@list) %>
  </div>

  <div class="btn btn-dark">
    <%= link_to 'Back to all lists', lists_path(@list) %>
  </div>
</div>